# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /u/apps/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /u/apps/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/u/apps/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/u/apps/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/u/apps/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/u/apps/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/u/apps/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/u/apps/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/u/apps/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/u/apps/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sbsdig

# Build rule for target.
sbsdig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sbsdig
.PHONY : sbsdig

# fast build rule for target.
sbsdig/fast:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/build
.PHONY : sbsdig/fast

sbsdig.o: sbsdig.cxx.o

.PHONY : sbsdig.o

# target to build an object file
sbsdig.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/sbsdig.cxx.o
.PHONY : sbsdig.cxx.o

sbsdig.i: sbsdig.cxx.i

.PHONY : sbsdig.i

# target to preprocess a source file
sbsdig.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/sbsdig.cxx.i
.PHONY : sbsdig.cxx.i

sbsdig.s: sbsdig.cxx.s

.PHONY : sbsdig.s

# target to generate assembly for a file
sbsdig.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/sbsdig.cxx.s
.PHONY : sbsdig.cxx.s

src/SBSDigAuxi.o: src/SBSDigAuxi.cxx.o

.PHONY : src/SBSDigAuxi.o

# target to build an object file
src/SBSDigAuxi.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o
.PHONY : src/SBSDigAuxi.cxx.o

src/SBSDigAuxi.i: src/SBSDigAuxi.cxx.i

.PHONY : src/SBSDigAuxi.i

# target to preprocess a source file
src/SBSDigAuxi.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.i
.PHONY : src/SBSDigAuxi.cxx.i

src/SBSDigAuxi.s: src/SBSDigAuxi.cxx.s

.PHONY : src/SBSDigAuxi.s

# target to generate assembly for a file
src/SBSDigAuxi.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.s
.PHONY : src/SBSDigAuxi.cxx.s

src/SBSDigBkgdGen.o: src/SBSDigBkgdGen.cxx.o

.PHONY : src/SBSDigBkgdGen.o

# target to build an object file
src/SBSDigBkgdGen.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o
.PHONY : src/SBSDigBkgdGen.cxx.o

src/SBSDigBkgdGen.i: src/SBSDigBkgdGen.cxx.i

.PHONY : src/SBSDigBkgdGen.i

# target to preprocess a source file
src/SBSDigBkgdGen.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.i
.PHONY : src/SBSDigBkgdGen.cxx.i

src/SBSDigBkgdGen.s: src/SBSDigBkgdGen.cxx.s

.PHONY : src/SBSDigBkgdGen.s

# target to generate assembly for a file
src/SBSDigBkgdGen.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.s
.PHONY : src/SBSDigBkgdGen.cxx.s

src/SBSDigGEMDet.o: src/SBSDigGEMDet.cxx.o

.PHONY : src/SBSDigGEMDet.o

# target to build an object file
src/SBSDigGEMDet.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o
.PHONY : src/SBSDigGEMDet.cxx.o

src/SBSDigGEMDet.i: src/SBSDigGEMDet.cxx.i

.PHONY : src/SBSDigGEMDet.i

# target to preprocess a source file
src/SBSDigGEMDet.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.i
.PHONY : src/SBSDigGEMDet.cxx.i

src/SBSDigGEMDet.s: src/SBSDigGEMDet.cxx.s

.PHONY : src/SBSDigGEMDet.s

# target to generate assembly for a file
src/SBSDigGEMDet.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.s
.PHONY : src/SBSDigGEMDet.cxx.s

src/SBSDigGEMPlane.o: src/SBSDigGEMPlane.cxx.o

.PHONY : src/SBSDigGEMPlane.o

# target to build an object file
src/SBSDigGEMPlane.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o
.PHONY : src/SBSDigGEMPlane.cxx.o

src/SBSDigGEMPlane.i: src/SBSDigGEMPlane.cxx.i

.PHONY : src/SBSDigGEMPlane.i

# target to preprocess a source file
src/SBSDigGEMPlane.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.i
.PHONY : src/SBSDigGEMPlane.cxx.i

src/SBSDigGEMPlane.s: src/SBSDigGEMPlane.cxx.s

.PHONY : src/SBSDigGEMPlane.s

# target to generate assembly for a file
src/SBSDigGEMPlane.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.s
.PHONY : src/SBSDigGEMPlane.cxx.s

src/SBSDigGEMSimDig.o: src/SBSDigGEMSimDig.cxx.o

.PHONY : src/SBSDigGEMSimDig.o

# target to build an object file
src/SBSDigGEMSimDig.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o
.PHONY : src/SBSDigGEMSimDig.cxx.o

src/SBSDigGEMSimDig.i: src/SBSDigGEMSimDig.cxx.i

.PHONY : src/SBSDigGEMSimDig.i

# target to preprocess a source file
src/SBSDigGEMSimDig.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.i
.PHONY : src/SBSDigGEMSimDig.cxx.i

src/SBSDigGEMSimDig.s: src/SBSDigGEMSimDig.cxx.s

.PHONY : src/SBSDigGEMSimDig.s

# target to generate assembly for a file
src/SBSDigGEMSimDig.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.s
.PHONY : src/SBSDigGEMSimDig.cxx.s

src/SBSDigPMTDet.o: src/SBSDigPMTDet.cxx.o

.PHONY : src/SBSDigPMTDet.o

# target to build an object file
src/SBSDigPMTDet.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o
.PHONY : src/SBSDigPMTDet.cxx.o

src/SBSDigPMTDet.i: src/SBSDigPMTDet.cxx.i

.PHONY : src/SBSDigPMTDet.i

# target to preprocess a source file
src/SBSDigPMTDet.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.i
.PHONY : src/SBSDigPMTDet.cxx.i

src/SBSDigPMTDet.s: src/SBSDigPMTDet.cxx.s

.PHONY : src/SBSDigPMTDet.s

# target to generate assembly for a file
src/SBSDigPMTDet.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.s
.PHONY : src/SBSDigPMTDet.cxx.s

src/SBSDigPMTSignal.o: src/SBSDigPMTSignal.cxx.o

.PHONY : src/SBSDigPMTSignal.o

# target to build an object file
src/SBSDigPMTSignal.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o
.PHONY : src/SBSDigPMTSignal.cxx.o

src/SBSDigPMTSignal.i: src/SBSDigPMTSignal.cxx.i

.PHONY : src/SBSDigPMTSignal.i

# target to preprocess a source file
src/SBSDigPMTSignal.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.i
.PHONY : src/SBSDigPMTSignal.cxx.i

src/SBSDigPMTSignal.s: src/SBSDigPMTSignal.cxx.s

.PHONY : src/SBSDigPMTSignal.s

# target to generate assembly for a file
src/SBSDigPMTSignal.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.s
.PHONY : src/SBSDigPMTSignal.cxx.s

src/g4sbs_data.o: src/g4sbs_data.cxx.o

.PHONY : src/g4sbs_data.o

# target to build an object file
src/g4sbs_data.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o
.PHONY : src/g4sbs_data.cxx.o

src/g4sbs_data.i: src/g4sbs_data.cxx.i

.PHONY : src/g4sbs_data.i

# target to preprocess a source file
src/g4sbs_data.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.i
.PHONY : src/g4sbs_data.cxx.i

src/g4sbs_data.s: src/g4sbs_data.cxx.s

.PHONY : src/g4sbs_data.s

# target to generate assembly for a file
src/g4sbs_data.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.s
.PHONY : src/g4sbs_data.cxx.s

src/g4sbs_tree.o: src/g4sbs_tree.cxx.o

.PHONY : src/g4sbs_tree.o

# target to build an object file
src/g4sbs_tree.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o
.PHONY : src/g4sbs_tree.cxx.o

src/g4sbs_tree.i: src/g4sbs_tree.cxx.i

.PHONY : src/g4sbs_tree.i

# target to preprocess a source file
src/g4sbs_tree.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.i
.PHONY : src/g4sbs_tree.cxx.i

src/g4sbs_tree.s: src/g4sbs_tree.cxx.s

.PHONY : src/g4sbs_tree.s

# target to generate assembly for a file
src/g4sbs_tree.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.s
.PHONY : src/g4sbs_tree.cxx.s

src/gmn_tree.o: src/gmn_tree.cxx.o

.PHONY : src/gmn_tree.o

# target to build an object file
src/gmn_tree.cxx.o:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o
.PHONY : src/gmn_tree.cxx.o

src/gmn_tree.i: src/gmn_tree.cxx.i

.PHONY : src/gmn_tree.i

# target to preprocess a source file
src/gmn_tree.cxx.i:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.i
.PHONY : src/gmn_tree.cxx.i

src/gmn_tree.s: src/gmn_tree.cxx.s

.PHONY : src/gmn_tree.s

# target to generate assembly for a file
src/gmn_tree.cxx.s:
	$(MAKE) -f CMakeFiles/sbsdig.dir/build.make CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.s
.PHONY : src/gmn_tree.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sbsdig"
	@echo "... sbsdig.o"
	@echo "... sbsdig.i"
	@echo "... sbsdig.s"
	@echo "... src/SBSDigAuxi.o"
	@echo "... src/SBSDigAuxi.i"
	@echo "... src/SBSDigAuxi.s"
	@echo "... src/SBSDigBkgdGen.o"
	@echo "... src/SBSDigBkgdGen.i"
	@echo "... src/SBSDigBkgdGen.s"
	@echo "... src/SBSDigGEMDet.o"
	@echo "... src/SBSDigGEMDet.i"
	@echo "... src/SBSDigGEMDet.s"
	@echo "... src/SBSDigGEMPlane.o"
	@echo "... src/SBSDigGEMPlane.i"
	@echo "... src/SBSDigGEMPlane.s"
	@echo "... src/SBSDigGEMSimDig.o"
	@echo "... src/SBSDigGEMSimDig.i"
	@echo "... src/SBSDigGEMSimDig.s"
	@echo "... src/SBSDigPMTDet.o"
	@echo "... src/SBSDigPMTDet.i"
	@echo "... src/SBSDigPMTDet.s"
	@echo "... src/SBSDigPMTSignal.o"
	@echo "... src/SBSDigPMTSignal.i"
	@echo "... src/SBSDigPMTSignal.s"
	@echo "... src/g4sbs_data.o"
	@echo "... src/g4sbs_data.i"
	@echo "... src/g4sbs_data.s"
	@echo "... src/g4sbs_tree.o"
	@echo "... src/g4sbs_tree.i"
	@echo "... src/g4sbs_tree.s"
	@echo "... src/gmn_tree.o"
	@echo "... src/gmn_tree.i"
	@echo "... src/gmn_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

