# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /u/apps/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /u/apps/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig

# Include any dependencies generated for this target.
include CMakeFiles/sbsdig.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/sbsdig.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/sbsdig.dir/flags.make

CMakeFiles/sbsdig.dir/sbsdig.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/sbsdig.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/sbsdig.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/sbsdig.dir/sbsdig.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/sbsdig.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/sbsdig.cxx

CMakeFiles/sbsdig.dir/sbsdig.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/sbsdig.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/sbsdig.cxx > CMakeFiles/sbsdig.dir/sbsdig.cxx.i

CMakeFiles/sbsdig.dir/sbsdig.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/sbsdig.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/sbsdig.cxx -o CMakeFiles/sbsdig.dir/sbsdig.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigAuxi.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigAuxi.cxx

CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigAuxi.cxx > CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigAuxi.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigBkgdGen.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigBkgdGen.cxx

CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigBkgdGen.cxx > CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigBkgdGen.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMDet.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMDet.cxx

CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMDet.cxx > CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMDet.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMPlane.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMPlane.cxx

CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMPlane.cxx > CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMPlane.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMSimDig.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMSimDig.cxx

CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMSimDig.cxx > CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigGEMSimDig.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTDet.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTDet.cxx

CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTDet.cxx > CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTDet.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.s

CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTSignal.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTSignal.cxx

CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTSignal.cxx > CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.i

CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/SBSDigPMTSignal.cxx -o CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.s

CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_data.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_data.cxx

CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_data.cxx > CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.i

CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_data.cxx -o CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.s

CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_tree.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_tree.cxx

CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_tree.cxx > CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.i

CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/g4sbs_tree.cxx -o CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.s

CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o: CMakeFiles/sbsdig.dir/flags.make
CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o: /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/gmn_tree.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o -c /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/gmn_tree.cxx

CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/gmn_tree.cxx > CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.i

CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src/gmn_tree.cxx -o CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.s

# Object files for target sbsdig
sbsdig_OBJECTS = \
"CMakeFiles/sbsdig.dir/sbsdig.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o" \
"CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o" \
"CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o" \
"CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o" \
"CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o"

# External object files for target sbsdig
sbsdig_EXTERNAL_OBJECTS =

sbsdig: CMakeFiles/sbsdig.dir/sbsdig.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigAuxi.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigBkgdGen.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigGEMDet.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigGEMPlane.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigGEMSimDig.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigPMTDet.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/SBSDigPMTSignal.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/g4sbs_data.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/g4sbs_tree.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/src/gmn_tree.cxx.o
sbsdig: CMakeFiles/sbsdig.dir/build.make
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libCore.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libImt.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libRIO.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libNet.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libHist.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libGraf.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libGraf3d.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libGpad.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libROOTDataFrame.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libTree.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libTreePlayer.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libRint.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libPostscript.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libMatrix.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libPhysics.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libMathCore.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libThread.so
sbsdig: /site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/lib/libMultiProc.so
sbsdig: CMakeFiles/sbsdig.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Linking CXX executable sbsdig"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/sbsdig.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/sbsdig.dir/build: sbsdig

.PHONY : CMakeFiles/sbsdig.dir/build

CMakeFiles/sbsdig.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/sbsdig.dir/cmake_clean.cmake
.PHONY : CMakeFiles/sbsdig.dir/clean

CMakeFiles/sbsdig.dir/depend:
	cd /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig /home/gautam/sbs_work/vgit4libsbsdg/libsbsdig /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig /w/halla-scifs17exp/sbs/thir/vgit4libsbsdg/libsbsdig/CMakeFiles/sbsdig.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/sbsdig.dir/depend

