# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# compile CXX with /usr/bin/c++
CXX_FLAGS =   -pipe -m64 -fsigned-char -pthread -std=c++11 -Wall -fPIC -O -g -Woverloaded-virtual -Wextra -Wno-missing-field-initializers  -pipe -m64 -fsigned-char -pthread -std=c++11 -g  

CXX_DEFINES = 

CXX_INCLUDES = -I/site/12gev_phys/2.3/Linux_CentOS7.7.1908-x86_64-gcc4.8.5/root/6.14.04/include -I//w/halla-scifs17exp/sbs/thir/g4_work/g4sbs_install/include -I/home/gautam/sbs_work/vgit4libsbsdg/libsbsdig/src 

